#pragma comment(lib, "dxguid.lib")
#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib,"d3dcompiler.lib")

#include <Windows.h>
#include <windowsx.h>
#include <dxgi.h>
#include <d3d11.h>
#include "../../../resources/format.h"

DXGI_FORMAT kResourceFormat[] = {
	DXGI_FORMAT_UNKNOWN,
	DXGI_FORMAT_R32G32B32A32_TYPELESS,
	DXGI_FORMAT_R32G32B32A32_FLOAT,
	DXGI_FORMAT_R32G32B32A32_UINT,
	DXGI_FORMAT_R32G32B32A32_SINT,
	DXGI_FORMAT_R32G32B32_TYPELESS,
	DXGI_FORMAT_R32G32B32_FLOAT,
	DXGI_FORMAT_R32G32B32_UINT,
	DXGI_FORMAT_R32G32B32_SINT,
	DXGI_FORMAT_R16G16B16A16_TYPELESS,
	DXGI_FORMAT_R16G16B16A16_FLOAT,
	DXGI_FORMAT_R16G16B16A16_UNORM,
	DXGI_FORMAT_R16G16B16A16_UINT,
	DXGI_FORMAT_R16G16B16A16_SNORM,
	DXGI_FORMAT_R16G16B16A16_SINT,
	DXGI_FORMAT_R32G32_TYPELESS,
	DXGI_FORMAT_R32G32_FLOAT,
	DXGI_FORMAT_R32G32_UINT,
	DXGI_FORMAT_R32G32_SINT,
	DXGI_FORMAT_R32G8X24_TYPELESS,
	DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
	DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
	DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
	DXGI_FORMAT_R10G10B10A2_TYPELESS,
	DXGI_FORMAT_R10G10B10A2_UNORM,
	DXGI_FORMAT_R10G10B10A2_UINT,
	DXGI_FORMAT_R11G11B10_FLOAT,
	DXGI_FORMAT_R8G8B8A8_TYPELESS,
	DXGI_FORMAT_R8G8B8A8_UNORM,
	DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
	DXGI_FORMAT_R8G8B8A8_UINT,
	DXGI_FORMAT_R8G8B8A8_SNORM,
	DXGI_FORMAT_R8G8B8A8_SINT,
	DXGI_FORMAT_R16G16_TYPELESS,
	DXGI_FORMAT_R16G16_FLOAT,
	DXGI_FORMAT_R16G16_UNORM,
	DXGI_FORMAT_R16G16_UINT,
	DXGI_FORMAT_R16G16_SNORM,
	DXGI_FORMAT_R16G16_SINT,
	DXGI_FORMAT_R32_TYPELESS,
	DXGI_FORMAT_D32_FLOAT,
	DXGI_FORMAT_R32_FLOAT,
	DXGI_FORMAT_R32_UINT,
	DXGI_FORMAT_R32_SINT,
	DXGI_FORMAT_R24G8_TYPELESS,
	DXGI_FORMAT_D24_UNORM_S8_UINT,
	DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
	DXGI_FORMAT_X24_TYPELESS_G8_UINT,
	DXGI_FORMAT_R8G8_TYPELESS,
	DXGI_FORMAT_R8G8_UNORM,
	DXGI_FORMAT_R8G8_UINT,
	DXGI_FORMAT_R8G8_SNORM,
	DXGI_FORMAT_R8G8_SINT,
	DXGI_FORMAT_R16_TYPELESS,
	DXGI_FORMAT_R16_FLOAT,
	DXGI_FORMAT_D16_UNORM,
	DXGI_FORMAT_R16_UNORM,
	DXGI_FORMAT_R16_UINT,
	DXGI_FORMAT_R16_SNORM,
	DXGI_FORMAT_R16_SINT,
	DXGI_FORMAT_R8_TYPELESS,
	DXGI_FORMAT_R8_UNORM,
	DXGI_FORMAT_R8_UINT,
	DXGI_FORMAT_R8_SNORM,
	DXGI_FORMAT_R8_SINT,
	DXGI_FORMAT_A8_UNORM,
	DXGI_FORMAT_R1_UNORM,
	DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
	DXGI_FORMAT_R8G8_B8G8_UNORM,
	DXGI_FORMAT_G8R8_G8B8_UNORM,
	DXGI_FORMAT_BC1_TYPELESS,
	DXGI_FORMAT_BC1_UNORM,
	DXGI_FORMAT_BC1_UNORM_SRGB,
	DXGI_FORMAT_BC2_TYPELESS,
	DXGI_FORMAT_BC2_UNORM,
	DXGI_FORMAT_BC2_UNORM_SRGB,
	DXGI_FORMAT_BC3_TYPELESS,
	DXGI_FORMAT_BC3_UNORM,
	DXGI_FORMAT_BC3_UNORM_SRGB,
	DXGI_FORMAT_BC4_TYPELESS,
	DXGI_FORMAT_BC4_UNORM,
	DXGI_FORMAT_BC4_SNORM,
	DXGI_FORMAT_BC5_TYPELESS,
	DXGI_FORMAT_BC5_UNORM,
	DXGI_FORMAT_BC5_SNORM,
	DXGI_FORMAT_B5G6R5_UNORM,
	DXGI_FORMAT_B5G5R5A1_UNORM,
	DXGI_FORMAT_B8G8R8A8_UNORM,
	DXGI_FORMAT_B8G8R8X8_UNORM,
	DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
	DXGI_FORMAT_B8G8R8A8_TYPELESS,
	DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
	DXGI_FORMAT_B8G8R8X8_TYPELESS,
	DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
	DXGI_FORMAT_BC6H_TYPELESS,
	DXGI_FORMAT_BC6H_UF16,
	DXGI_FORMAT_BC6H_SF16,
	DXGI_FORMAT_BC7_TYPELESS,
	DXGI_FORMAT_BC7_UNORM,
	DXGI_FORMAT_BC7_UNORM_SRGB,
	DXGI_FORMAT_AYUV,
	DXGI_FORMAT_Y410,
	DXGI_FORMAT_Y416,
	DXGI_FORMAT_NV12,
	DXGI_FORMAT_P010,
	DXGI_FORMAT_P016,
	DXGI_FORMAT_420_OPAQUE,
	DXGI_FORMAT_YUY2,
	DXGI_FORMAT_Y210,
	DXGI_FORMAT_Y216,
	DXGI_FORMAT_NV11,
	DXGI_FORMAT_AI44,
	DXGI_FORMAT_IA44,
	DXGI_FORMAT_P8,
	DXGI_FORMAT_A8P8,
	DXGI_FORMAT_B4G4R4A4_UNORM,
	DXGI_FORMAT_FORCE_UINT
};

ID3D11Device* pDevice = NULL;
ID3D11DeviceContext* pContext = NULL;
HWND gWindowHandle = NULL;
IDXGISwapChain* pSwapChain = NULL;

uint32_t lu::GetResourceFormatBitsPerPixel(ResourceFormat format)
{
	switch (format)
	{
	case ResourceFormat::FORMAT_R32G32B32A32_TYPELESS:
	case ResourceFormat::FORMAT_R32G32B32A32_FLOAT:
	case ResourceFormat::FORMAT_R32G32B32A32_UINT:
	case ResourceFormat::FORMAT_R32G32B32A32_SINT:
		return 128;

	case ResourceFormat::FORMAT_R32G32B32_TYPELESS:
	case ResourceFormat::FORMAT_R32G32B32_FLOAT:
	case ResourceFormat::FORMAT_R32G32B32_UINT:
	case ResourceFormat::FORMAT_R32G32B32_SINT:
		return 96;

	case ResourceFormat::FORMAT_R16G16B16A16_TYPELESS:
	case ResourceFormat::FORMAT_R16G16B16A16_FLOAT:
	case ResourceFormat::FORMAT_R16G16B16A16_UNORM:
	case ResourceFormat::FORMAT_R16G16B16A16_UINT:
	case ResourceFormat::FORMAT_R16G16B16A16_SNORM:
	case ResourceFormat::FORMAT_R16G16B16A16_SINT:
	case ResourceFormat::FORMAT_R32G32_TYPELESS:
	case ResourceFormat::FORMAT_R32G32_FLOAT:
	case ResourceFormat::FORMAT_R32G32_UINT:
	case ResourceFormat::FORMAT_R32G32_SINT:
	case ResourceFormat::FORMAT_R32G8X24_TYPELESS:
	case ResourceFormat::FORMAT_D32_FLOAT_S8X24_UINT:
	case ResourceFormat::FORMAT_R32_FLOAT_X8X24_TYPELESS:
	case ResourceFormat::FORMAT_X32_TYPELESS_G8X24_UINT:
	case ResourceFormat::FORMAT_Y416:
	case ResourceFormat::FORMAT_Y210:
	case ResourceFormat::FORMAT_Y216:
		return 64;

	case ResourceFormat::FORMAT_R10G10B10A2_TYPELESS:
	case ResourceFormat::FORMAT_R10G10B10A2_UNORM:
	case ResourceFormat::FORMAT_R10G10B10A2_UINT:
	case ResourceFormat::FORMAT_R11G11B10_FLOAT:
	case ResourceFormat::FORMAT_R8G8B8A8_TYPELESS:
	case ResourceFormat::FORMAT_R8G8B8A8_UNORM:
	case ResourceFormat::FORMAT_R8G8B8A8_UNORM_SRGB:
	case ResourceFormat::FORMAT_R8G8B8A8_UINT:
	case ResourceFormat::FORMAT_R8G8B8A8_SNORM:
	case ResourceFormat::FORMAT_R8G8B8A8_SINT:
	case ResourceFormat::FORMAT_R16G16_TYPELESS:
	case ResourceFormat::FORMAT_R16G16_FLOAT:
	case ResourceFormat::FORMAT_R16G16_UNORM:
	case ResourceFormat::FORMAT_R16G16_UINT:
	case ResourceFormat::FORMAT_R16G16_SNORM:
	case ResourceFormat::FORMAT_R16G16_SINT:
	case ResourceFormat::FORMAT_R32_TYPELESS:
	case ResourceFormat::FORMAT_D32_FLOAT:
	case ResourceFormat::FORMAT_R32_FLOAT:
	case ResourceFormat::FORMAT_R32_UINT:
	case ResourceFormat::FORMAT_R32_SINT:
	case ResourceFormat::FORMAT_R24G8_TYPELESS:
	case ResourceFormat::FORMAT_D24_UNORM_S8_UINT:
	case ResourceFormat::FORMAT_R24_UNORM_X8_TYPELESS:
	case ResourceFormat::FORMAT_X24_TYPELESS_G8_UINT:
	case ResourceFormat::FORMAT_R9G9B9E5_SHAREDEXP:
	case ResourceFormat::FORMAT_R8G8_B8G8_UNORM:
	case ResourceFormat::FORMAT_G8R8_G8B8_UNORM:
	case ResourceFormat::FORMAT_B8G8R8A8_UNORM:
	case ResourceFormat::FORMAT_B8G8R8X8_UNORM:
	case ResourceFormat::FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
	case ResourceFormat::FORMAT_B8G8R8A8_TYPELESS:
	case ResourceFormat::FORMAT_B8G8R8A8_UNORM_SRGB:
	case ResourceFormat::FORMAT_B8G8R8X8_TYPELESS:
	case ResourceFormat::FORMAT_B8G8R8X8_UNORM_SRGB:
	case ResourceFormat::FORMAT_AYUV:
	case ResourceFormat::FORMAT_Y410:
	case ResourceFormat::FORMAT_YUY2:
		return 32;

	case ResourceFormat::FORMAT_P010:
	case ResourceFormat::FORMAT_P016:
		return 24;

	case ResourceFormat::FORMAT_R8G8_TYPELESS:
	case ResourceFormat::FORMAT_R8G8_UNORM:
	case ResourceFormat::FORMAT_R8G8_UINT:
	case ResourceFormat::FORMAT_R8G8_SNORM:
	case ResourceFormat::FORMAT_R8G8_SINT:
	case ResourceFormat::FORMAT_R16_TYPELESS:
	case ResourceFormat::FORMAT_R16_FLOAT:
	case ResourceFormat::FORMAT_D16_UNORM:
	case ResourceFormat::FORMAT_R16_UNORM:
	case ResourceFormat::FORMAT_R16_UINT:
	case ResourceFormat::FORMAT_R16_SNORM:
	case ResourceFormat::FORMAT_R16_SINT:
	case ResourceFormat::FORMAT_B5G6R5_UNORM:
	case ResourceFormat::FORMAT_B5G5R5A1_UNORM:
	case ResourceFormat::FORMAT_A8P8:
	case ResourceFormat::FORMAT_B4G4R4A4_UNORM:
		return 16;

	case ResourceFormat::FORMAT_NV12:
	case ResourceFormat::FORMAT_420_OPAQUE:
	case ResourceFormat::FORMAT_NV11:
		return 12;

	case ResourceFormat::FORMAT_R8_TYPELESS:
	case ResourceFormat::FORMAT_R8_UNORM:
	case ResourceFormat::FORMAT_R8_UINT:
	case ResourceFormat::FORMAT_R8_SNORM:
	case ResourceFormat::FORMAT_R8_SINT:
	case ResourceFormat::FORMAT_A8_UNORM:
	case ResourceFormat::FORMAT_AI44:
	case ResourceFormat::FORMAT_IA44:
	case ResourceFormat::FORMAT_P8:
		return 8;

	case ResourceFormat::FORMAT_R1_UNORM:
		return 1;

	case ResourceFormat::FORMAT_BC1_TYPELESS:
	case ResourceFormat::FORMAT_BC1_UNORM:
	case ResourceFormat::FORMAT_BC1_UNORM_SRGB:
	case ResourceFormat::FORMAT_BC4_TYPELESS:
	case ResourceFormat::FORMAT_BC4_UNORM:
	case ResourceFormat::FORMAT_BC4_SNORM:
		return 4;

	case ResourceFormat::FORMAT_BC2_TYPELESS:
	case ResourceFormat::FORMAT_BC2_UNORM:
	case ResourceFormat::FORMAT_BC2_UNORM_SRGB:
	case ResourceFormat::FORMAT_BC3_TYPELESS:
	case ResourceFormat::FORMAT_BC3_UNORM:
	case ResourceFormat::FORMAT_BC3_UNORM_SRGB:
	case ResourceFormat::FORMAT_BC5_TYPELESS:
	case ResourceFormat::FORMAT_BC5_UNORM:
	case ResourceFormat::FORMAT_BC5_SNORM:
	case ResourceFormat::FORMAT_BC6H_TYPELESS:
	case ResourceFormat::FORMAT_BC6H_UF16:
	case ResourceFormat::FORMAT_BC6H_SF16:
	case ResourceFormat::FORMAT_BC7_TYPELESS:
	case ResourceFormat::FORMAT_BC7_UNORM:
	case ResourceFormat::FORMAT_BC7_UNORM_SRGB:
		return 8;

	default:
		return 0;
	}
}
uint32_t lu::GetResourceFormatBytesPerPixel(ResourceFormat format)
{
	return GetResourceFormatBitsPerPixel(format) / 8;
}
